# Generated by Django 2.0.4 on 2020-01-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, '运维人员'), (2, '值班人员'), (0, '系统管理员')], default=2),
        ),
    ]
