# Generated by Django 2.0.4 on 2019-05-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190506_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, '运维人员'), (2, '值班人员'), (0, '系统管理员')], default=2),
        ),
    ]
