# Generated by Django 2.0.4 on 2019-05-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(0, '系统管理员'), (1, '运维人员'), (2, '值班人员')], default=2),
        ),
    ]
