# Generated by Django 2.0.4 on 2019-05-21 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskdo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opslogmodel',
            old_name='hosts',
            new_name='host',
        ),
        migrations.RemoveField(
            model_name='opslogmodel',
            name='group',
        ),
    ]
