# Generated by Django 2.0.4 on 2019-05-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskdo', '0002_auto_20190521_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='opslogmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
