# Generated by Django 2.0.4 on 2019-05-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskdo', '0003_opslogmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opslogmodel',
            name='cmd',
            field=models.CharField(max_length=200, null=True, verbose_name='操作命令'),
        ),
    ]
