# Generated by Django 2.0.4 on 2019-05-21 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskdo', '0004_opslogmodel_cmd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpsLogModel',
            new_name='OpsLog',
        ),
    ]
