# Generated by Django 2.0.4 on 2019-03-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostsinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsinfo',
            name='mac_address',
            field=models.CharField(default='', max_length=512, null=True, verbose_name='mac地址列表'),
        ),
        migrations.AlterField(
            model_name='hostsinfo',
            name='mathine_type',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='机器的类型 1=物理服务器,2=虚拟资产,3=网络设备 0=其他类型(未知)'),
        ),
        migrations.AlterField(
            model_name='hostsinfo',
            name='sn',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='SN－主机的唯一标示'),
        ),
        migrations.AlterField(
            model_name='hostsinfo',
            name='sn_key',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='唯一设备ID'),
        ),
    ]
