# Generated by Django 2.0.4 on 2019-05-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostsinfo', '0003_auto_20190419_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostgroup',
            name='host_num',
        ),
    ]
